name: release

on: 
  push:
    tags:
      - '*'
env:
  GO111MODULE: on
  GOPROXY: https://goproxy.cn,direct

jobs:
  release:
    runs-on: linux
    steps:
      - uses: https://gitea.lan/actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: https://gitea.lan/actions/setup-go@v3
        with:
          go-version: '>=1.20.1'
      - name: build-linux-arm
        run: GOOS=linux GOARCH=arm GOARM=7 go build -ldflags="-s -w -X 'main.Version=${{  gitea.ref }}'" -o bin/linux-arm
      - name: build-linux-arm64
        run: GOOS=linux GOARCH=arm64 go build -ldflags="-s -w -X 'main.Version=${{  gitea.ref }}'" -o bin/linux-arm64
      - name: build-linux-amd64
        run: GOOS=linux GOARCH=amd64 go build -ldflags="-s -w -X 'main.Version=${{  gitea.ref }}'" -o bin/linux-amd64
      - name: build-darwin-amd64
        run: GOOS=darwin GOARCH=amd64 go build -ldflags="-s -w -X 'main.Version=${{  gitea.ref }}'" -o bin/darwin-amd64
      - name: build-windows-amd64
        run: GOOS=windows GOARCH=amd64 go build -ldflags="-s -w -X 'main.Version=${{  gitea.ref }}'" -o bin/windows-amd64.exe
      - uses: https://gitea.lan/actions/release-action@main
        with:
          files: |-
            bin/**            
          api_key: '${{secrets.RELEASE_TOKEN}}'